CREATE TABLE [dbo].[Book]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID(),
	[Title] NVARCHAR(50) NOT NULL,
	[Desc] NVARCHAR(2000) NULL,
	[StatusId] INT NOT NULL,
	[Create_Date] DATETIME2 DEFAULT GETDATE(),

	CONSTRAINT PK_Book PRIMARY KEY ([Id]),
	CONSTRAINT FK_Book__Book_Status 
		FOREIGN KEY([StatusId])
		REFERENCES [Book_Status]([Id])
)
